services:
  appium:
    image: appium/appium:latest
    container_name: appium-server
    privileged: true
    ports:
      - "4723:4723"
    environment:
      - ALLOW_INSECURE=adb_shell
    networks:
      - mobile-testing
    restart: always
 
networks:
  mobile-testing:
    driver: bridge